-- Création de la table de pointage si vous préférez créer le schéma via SQL
-- (Alternative à la création automatique par Hibernate)

create table if not exists time_entry (
    id              bigint generated by default as identity primary key,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    employee_id     bigint not null references employee(id),
    entry_date      date not null,
    check_in        timestamp(6),
    check_out       timestamp(6),
    hours_worked    double precision,
    overtime_hours  double precision,
    late_minutes    integer,
    break_minutes   integer,
    entry_type      varchar(50),
    note            text
);
